### ISSUE TITLE
AttributeError: 'MainWindow' object has no attribute 'is_dell_g15'

### ISSUE THREAD

**Issue by ktheticdev** [cemkaya-mpi/Dell-G15-Controller#10]
I have a Dell G15 5515. When i try to launch the program, it fails.

```
QApplication: invalid style override 'kvantum' passed, ignoring it.
	Available styles: Windows, Fusion
Traceback (most recent call last):
  File "/home/weiss/Dell-G15-Controller/./main.py", line 449, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "/home/weiss/Dell-G15-Controller/./main.py", line 26, in __init__
    self.init_acpi_call()
  File "/home/weiss/Dell-G15-Controller/./main.py", line 97, in init_acpi_call
    if self.is_dell_g15:
       ^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'is_dell_g15'
```

**Comment by cemkaya-mpi** [comment]
Do you have the acpi_call module already loaded?

**Comment by ktheticdev** [comment]
yes I do

**Comment by cemkaya-mpi** [comment]
Alright. It seems only 5525 and 5520 are supported so far, and you have the 5515. However, I do not imagine the ACPI calls for 5515 is that different. If you want to, you can create a pull request for your model and I will be more than happy to accept it. 

You can check the `checkLaptapModel()` function and `patch.py` to see how @poly000 added support for the 5520.

Here is what needs to be done:
You need to determine which device to use: For the 5525, it was `_SB.AMW3.WMAX`, and for the 5520, it was `\_SB.AMWW.WMAX`. You can find this in your [dsdt.dsl](https://wiki.archlinux.org/title/DSDT)

Afterward, you need to try all power methods and see which ones work on your device: You can check the power_modes_dict and acpi_call_dict for this. Based on this, create a patch in patch.py for your model.

For your convenience, I will provide an example:
To switch to balanced power mode (0xa0) on the g15 5525:
`echo "\_SB.AMW3.WMAX 0 0x15 {1, 0xa0, 0x00, 0x00}" > /proc/acpi/call; cat /proc/acpi/call`
To read the current power mode:
 `echo "\_SB.AMW3.WMAX 0 0x14 {0xb, 0x00, 0x00, 0x00}"  > /proc/acpi/call; cat /proc/acpi/call`

After you try all acpi calls and confirm they work, you can create a pull request for your model. Feel free to reach out if you have questions.

**Comment by cemkaya-mpi** [comment]
Commit 99afb49 should fix the application crash.
