### ISSUE TITLE
Dell G15 5511 Intel edition SSDT table

### ISSUE THREAD

**Issue by MoveCloudROY** [cemkaya-mpi/Dell-G15-Controller#14]
I went through the past Issue and tried to export my computer's SSDT table, in which I found the WMAX method. 
[ssdt2.txt](https://github.com/cemkaya-mpi/Dell-G15-Controller/files/14979432/ssdt2.txt)
I also tried the scripts in #12 after changing `AMW3` to `AMWW`. 
```bash
#!/bin/bash

c(){ echo "$1" | sudo tee /proc/acpi/call >/dev/null && sudo cat /proc/acpi/call;echo;}

for mode in 0xa{0..9} 0xa{a..b}
do
    echo "Trying mode ${mode}"
    echo "\_SB.AMWW.WMAX 0 0x15 {0x01, ${mode}, 0x00, 0x00}"
    c "\_SB.AMWW.WMAX 0 0x15 {0x01, ${mode}, 0x00, 0x00}"
done
echo "Reverting to balanced."
c "\_SB.AMWW.WMAX 0 0x15 {0x01, 0xa0, 0x00, 0x00}"
```
The results are as follows:
```bash
Trying mode 0xa0
\_SB.AMWW.WMAX 0 0x15 {0x01, 0xa0, 0x00, 0x00}
0x0
Trying mode 0xa1
\_SB.AMWW.WMAX 0 0x15 {0x01, 0xa1, 0x00, 0x00}
0x0
Trying mode 0xa2
\_SB.AMWW.WMAX 0 0x15 {0x01, 0xa2, 0x00, 0x00}
0x0
Trying mode 0xa3
\_SB.AMWW.WMAX 0 0x15 {0x01, 0xa3, 0x00, 0x00}
0x0
Trying mode 0xa4
\_SB.AMWW.WMAX 0 0x15 {0x01, 0xa4, 0x00, 0x00}
0xffffffff
Trying mode 0xa5
\_SB.AMWW.WMAX 0 0x15 {0x01, 0xa5, 0x00, 0x00}
0xffffffff
Trying mode 0xa6
\_SB.AMWW.WMAX 0 0x15 {0x01, 0xa6, 0x00, 0x00}
0xffffffff
Trying mode 0xa7
\_SB.AMWW.WMAX 0 0x15 {0x01, 0xa7, 0x00, 0x00}
0xffffffff
Trying mode 0xa8
\_SB.AMWW.WMAX 0 0x15 {0x01, 0xa8, 0x00, 0x00}
0xffffffff
Trying mode 0xa9
\_SB.AMWW.WMAX 0 0x15 {0x01, 0xa9, 0x00, 0x00}
0xffffffff
Trying mode 0xaa
\_SB.AMWW.WMAX 0 0x15 {0x01, 0xaa, 0x00, 0x00}
0xffffffff
Trying mode 0xab
\_SB.AMWW.WMAX 0 0x15 {0x01, 0xab, 0x00, 0x00}
0x0
Reverting to balanced.
0x0

```

**Comment by MoveCloudROY** [comment]
I think these are valid on the g5511
```python
public enum ThermalMode
{
    Custom = 0,                     
    Quiet = 150,
    Balanced = 151,                
    Performance = 152,
    FullSpeed = 153,
    # USTT_Balanced = 160,
    # USTT_Performance = 161,
    # USTT_Cool = 162,
    # USTT_Quiet = 163,
    # USTT_FullSpeed = 164,
    # USTT_BatterySaver = 165,
    G_Mode = 171                   
}
```

**Comment by cemkaya-mpi** [comment]
This is great news! As I do not have too much free time nowadays, it might take me a while to update the code. @MoveCloudROY could you create a PR for the patch? You can add the dict to patch.py and add your laptop model to checkLaptopModel()

**Comment by cemkaya-mpi** [comment]
Hi, could you try the [G15_5511](https://github.com/cemkaya-mpi/Dell-G15-Controller/tree/G15_5511) branch to confirm that it works?

**Comment by cemkaya-mpi** [comment]
Hmm, maybe getting the current power mode returns USTT_Balanced when the mode is set to Balanced and so on? That error message seems to suggest so. That doesn't necessarily mean that setting the power mode does not work.

Could you test whether switching from balanced  or performance to quiet and vice versa has no effect on

- Cpu max temperature: On the 5525, balanced is around 92, Performance goes up to 100, Quiet is about 90 etc.
- Fan speed under load: For quiet this is about 3300/3600rpm versus 4000+/5000+ on balanced and performance mode.

**Comment by Phobeuscz** [comment]
To be honest, it even stopped detecting it's 5511.
Offering me only methods for 5525.
Flashing BIOS didn't helped

**Comment by Phobeuscz** [comment]
I've modified it that it's working fine for me, switching fan profiles like a charm, after debugging for a while.

main.py Line 107
`5511: ("echo \"\\_SB.AMWW.WMAX 0 {} {{{}, {}, {}, 0x00}}\" > /proc/acpi/call; cat /proc/acpi/call", None), # g15_5511_patch),`

in comment is what was there

**Comment by cemkaya-mpi** [comment]
Hi, thanks for your contributions! I would be more than happy to accept these changes if you make a PR for them and they work well.

**Comment by cemkaya-mpi** [comment]
Support for G15 5511 added with v3.7
