### ISSUE TITLE
Power mode works on Alienware M16 R1 model, keyboard lights do not.

### ISSUE THREAD

**Issue by arabcian** [cemkaya-mpi/Dell-G15-Controller#22]
Selam kardesim umutsuzca internette dolasirken programina rastladim acpi_call modulunu yukleyince laptopumda platform profillerini degistirebiliyorum. Klavye isiklarini kontrol etmeyi denemedim daha cok da onemli degiller zaten. Ne guzel insanlar var dunyada, cok tesekkurler.

**Comment by cemkaya-mpi** [comment]
That is great to hear. For the keyboard backlights on the Alienware model, the zones would probably have to be redefined as Alienware models tend to have more LEDs for the lid, power button etc. If you are interested, please take a look at [this issue](https://github.com/cemkaya-mpi/Dell-G15-Controller/issues/21).

**Comment by cemkaya-mpi** [comment]
Closing this issue, feel free to open it with more information to add keyboard backlight support.

**Comment by arabcian** [comment]
Hello Again Cem after alienware-wmi getting support from kurt borja i stopped using program but wanted to give a go yesterday while now my keyboard is recognised and have some led control working on it. I somehow managed to shutdown my power button led while playing with settings. Now no matter what i do my power button doesnt light up as it has indicate some system incidents im needing it. I dont have windows and i cant install it because im afraid that im going to get my bios updated to a broken version(its a problem with my model) is there any way to reset keyboard lights to default any knob for it that i can use acpi_call to reset?

**Comment by cemkaya-mpi** [comment]
You can either try to change the zones list in awelc.py or install windows in a VM with an AWCC alternative and passthrough the usb device to it.

**Comment by arabcian** [comment]
Oh thank you for the ideas.
