### ISSUE TITLE
Laptop model not supported after kernel downgrade

### ISSUE THREAD

**Issue by matheus-mr** [cemkaya-mpi/Dell-G15-Controller#23]
I had to downgrade my kernel from 6.9.9.arch1-1 to 6.0.10-arch2-1 to be able to use an old nvidia driver (520.56.06) because the latest is causing games to freeze due to the xid 109 problem: https://forums.developer.nvidia.com/t/multiple-cuda-rtx-vulkan-application-crashing-with-xid-13-109-errors/235459/399. 

After that Dell G15 Controller stopped working for me. It says my laptop model is not supported.

Do I need to downgrade Dell G15 Controller as well?

My specs:

```
OS: Arch Linux x86_64
Host: Dell G15 5525 (1.16.1)
Kernel: Linux 6.0.10-arch2-1
CPU: AMD Ryzen 7 6800H (16) @ 3.20 GHz
GPU 1: AMD Radeon 680M [Integrated]
GPU 2: NVIDIA GeForce RTX 3060 Mobile / Max-Q [Discrete]
```

**Comment by cemkaya-mpi** [comment]
Unless you have the dkms variant, you should rebuild the acpi call kernel module.

**Comment by matheus-mr** [comment]
Thanks! I switched to dkms variant and it's working now.
