### ISSUE TITLE
Works on Dell G16 7620

### ISSUE THREAD

**Issue by JL2210** [cemkaya-mpi/Dell-G15-Controller#24]
Not too surprising, these devices are very similar. I think they even use the same BIOS.

Recommend replacing `GROUP="plugdev"` with `TAG+="uaccess"`. This is [best practice](https://wiki.archlinux.org/title/Udev#Allowing_regular_users_to_use_devices) on Arch Linux. Then you can just check whether or not you can access the file rather than if you're in the group.

Keyboard backlight does not work with Secure Boot in Audit mode. Don't ask me how long I took to figure this out.

![image](https://github.com/user-attachments/assets/66eb8f6d-1107-4fd7-a18c-1005b6a44654)

Also keybinds from fn+f7 and fn+f9 to toggle keyboard lights and G mode respectively would be nice-to-have

**Comment by cemkaya-mpi** [comment]
Hi, thanks for the information. Pull requests are more than welcome if you would like to add functionality.

**Comment by cemkaya-mpi** [comment]
For the secure boot in audit mode, probably WMI is the way to go (this is how AWCC does it AFAIK).

Ideally this project should have a kernel module that does this, and the GUI should interface with the module. But I unfortunately do not have enough time to develop this project further.

**Comment by cemkaya-mpi** [comment]
Closing this issue as it works out of the box for the G16 7620.
