### ISSUE TITLE
Power and fan management does not work on custom bash prompts

### ISSUE THREAD

**Issue by cemkaya-mpi** [cemkaya-mpi/Dell-G15-Controller#3]
If the bash prompt does not end with '$' or '#', the app waits for the child bash process to print these values to stdout until timeout, and fan and power related functions do not work as a result. The current workaround is to have an unmodified bash prompt, but this is not optimal. It would be better to detect the current bash prompt and wait for it instead.

**Comment by poly000** [comment]
call sh -c "..." may worth a try
