### ISSUE TITLE
G15 5520 compatibility

### ISSUE THREAD

**Issue by walter-gabriel** [cemkaya-mpi/Dell-G15-Controller#4]
Hello! I have a Dell G15 5520, and would want to add it as compatible, to add at least G button function and put the fans to the max. How can I intercept AWCC ACPI commands from windows? I tried extracting DSDT, and reading ACPI tables, but couldn't compile it to even try to locate some functions.

**Comment by cemkaya-mpi** [comment]
Hi, the ACPI calls should be similar. Do you have the following in your dsdt? If so, could you share it with me?

```
Scope (_SB){
        Device (AMW3)
        ...
        Method (WMAX, 3, Serialized) {
        ...
```

**Comment by cemkaya-mpi** [comment]
To get G mode, you should set power mode to 0xab and toggle the G mode. You can look at [the arch wiki](https://wiki.archlinux.org/title/Dell_G15_5525) to see the acpi calls for the dell G15 5525.

**Comment by walter-gabriel** [comment]
Hello. This entry does not exist in my DSDT. I think the architecture is very different, being a Intel based PC.
[dsdt.zip](https://github.com/cemkaya-mpi/Dell-G15-Controller/files/12569789/dsdt.zip)

**Comment by walter-gabriel** [comment]
Found the WMAX method in another table. Maybe it is the one?
[ssdt1.zip](https://github.com/cemkaya-mpi/Dell-G15-Controller/files/12569965/ssdt1.zip)

**Comment by walter-gabriel** [comment]
Found it! It worked. Switched from AMW3 to AMWW, working good. USTT_FullSpeed not working.

**Comment by cemkaya-mpi** [comment]
Great! If I recall correctly, there was an acpi call that returned the system id. That call could be used to determine the laptop model and choose the correct acpi calls for power and fan control. On the G15 5525, 
`"\_SB.AMW3.WMAX 0 0x1a {2, 2, 0x00, 0x00}"`
returns
`0x12c0.`

If you share the result on your laptop, we could add a detection mechanism on startup. There might also be other power modes available on your model, such as the following:

```
public enum ThermalMode
{
    Custom = 0,                     
    Quiet = 150,
    Balanced = 151,                
    Performance = 152,
    FullSpeed = 153,
    USTT_Balanced = 160,
    USTT_Performance = 161,
    USTT_Cool = 162,
    USTT_Quiet = 163,
    USTT_FullSpeed = 164,
    USTT_BatterySaver = 165,
    G_Mode = 171                   
}
```

Could you also tell me which of these work?

**Comment by cemkaya-mpi** [comment]
```
sudo modprobe acpi_call
c(){ echo "$1" | sudo tee /proc/acpi/call >/dev/null && sudo cat /proc/acpi/call;echo;}
```

To set a power mode, you can run

`c "\_SB.AMW3.WMAX 0 0x15 {1, MODE, 0x00, 0x00}"`

To get the current mode, you can run

`c "\_SB.AMW3.WMAX 0 0x14 {0xb, 0x00, 0x00, 0x00}"`

I believe you will have to replace `AMW3` with `AMWW`.

**Comment by walter-gabriel** [comment]
`echo "\_SB.AMW3.WMAX 0 0x1a {2, 2, 0x00, 0x00}" > /proc/acpi/call; cat /proc/acpi/call`
returns
`Error: AE_NOT_FOUND`
`
echo "\_SB.AMWW.WMAX 0 0x1a {2, 2, 0x00, 0x00}" > /proc/acpi/call; cat /proc/acpi/call`
returns
`0x12c0`

Modes Quiet 150, Balanced 151, Performance 152, FullSpeed 153, USTT_Cool 162, USTT_FullSpeed 164
returns
'0xffffffff' which basicaly dont works XD

**Comment by walter-gabriel** [comment]
I truly dont know my way around python. I edited main.py without messing with the conditionals XD. Sorry but I cannot help sir.
